spring:
  datasource:
    url: jdbc:h2:mem:colegio_db;
    driverClassName: org.h2.Driver
    username: admin
    password: 12345*
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  application:
    name: colegio-app
